---
- import_tasks: wait_for_loadbalancer.yml

- name: Creating the Mariabackup database
  become: true
  kolla_toolbox:
    module_name: mysql_db
    module_args:
      login_host: "{{ database_address }}"
      login_port: "{{ database_port }}"
      login_user: "{{ database_user }}"
      login_password: "{{ database_password }}"
      name: "{{ mariadb_backup_database_schema }}"
  run_once: True
  when:
    - enable_mariabackup | bool

- name: Creating database backup user and setting permissions
  become: true
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ database_address }}"
      login_port: "{{ database_port }}"
      login_user: "{{ database_user }}"
      login_password: "{{ database_password }}"
      name: "{{ mariadb_backup_database_user }}"
      password: "{{ mariadb_backup_database_password }}"
      host: "%"
      priv: "*.*:CREATE TABLESPACE,RELOAD,PROCESS,SUPER,LOCK TABLES,REPLICATION CLIENT"
      append_privs: True
  run_once: True
  when:
    - enable_mariabackup | bool

- name: Granting permissions on Mariabackup database to backup user
  become: true
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ database_address }}"
      login_port: "{{ database_port }}"
      login_user: "{{ database_user }}"
      login_password: "{{ database_password }}"
      name: "{{ mariadb_backup_database_user }}"
      password: "{{ mariadb_backup_database_password }}"
      host: "%"
      priv: "{{ mariadb_backup_database_schema }}.*:CREATE,INSERT,SELECT"
      append_privs: True
  run_once: True
  when:
    - enable_mariabackup | bool
