---
- name: Checking host OS distribution
  fail:
    msg: >-
      Host OS distribution {{ ansible_distribution }} is not supported.
      Supported distributions are: {{ host_os_distributions.keys() | join(', ') }}
  when: ansible_distribution not in host_os_distributions

- name: Checking host OS release or version
  fail:
    msg: >-
      {{ ansible_distribution }} release {{ ansible_distribution_release }}
      version {{ ansible_distribution_version }} is not supported.
      Supported releases are:
      {{ host_os_distributions[ansible_distribution] | join(', ') }}
  when:
    - ansible_distribution_release not in host_os_distributions[ansible_distribution]
    - ansible_distribution_version not in host_os_distributions[ansible_distribution]
    - ansible_distribution_major_version not in host_os_distributions[ansible_distribution]
