---
- include_tasks: register.yml
  when: inventory_hostname in groups['masakari-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['masakari-api'] or
        inventory_hostname in groups['masakari-engine'] or
        inventory_hostname in groups['masakari-monitors']

- include_tasks: clone.yml
  when: masakari_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['masakari-api']

- name: Flush handlers
  meta: flush_handlers
