---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ chrony_services }}"
    service_name: "{{ project_name }}"

# TODO(Jeffrey4l), need check whether udp 123 port is used. But there is no
# module to do this now.
