---
# TODO(dszumski): Remove this in the V cycle once all old containers have been
# stopped.
- name: Stopping old monasca-log-api containers
  become: true
  kolla_docker:
    action: "stop_and_remove_container"
    common_options: "{{ docker_common_options }}"
    name: "monasca_log_api"

- include_tasks: config.yml

- include_tasks: register.yml
  when: inventory_hostname in groups['monasca-api']

- include_tasks: bootstrap_service.yml

- name: Flush handlers
  meta: flush_handlers
