---
- include_tasks: config.yml

- include_tasks: bootstrap_service.yml

# NOTE(priteau): Remove this task in V cycle.
- name: Remove heat-engine environment file
  become: true
  file:
    path: "{{ node_config_directory }}/heat-engine/_deprecated.yaml"
    state: absent

- name: Flush handlers
  meta: flush_handlers
