---
- include_tasks: register.yml
  when: inventory_hostname in groups['senlin-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['senlin-api'] or
        inventory_hostname in groups['senlin-conductor'] or
        inventory_hostname in groups['senlin-engine'] or
        inventory_hostname in groups['senlin-health-manager']

- include_tasks: clone.yml
  when: senlin_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['senlin-api']

- name: Flush handlers
  meta: flush_handlers
